//Incident Status
const RESOLVED_INCIDENT = "RESOLVED";
const PENDING_INCIDENT = "PENDING";

//Incident Type
const DOUBT_INCIDENT = "DOUBT";
const INTEGRATION_INCIDENT = "INTEGRATION";
const ORDER_INCIDENT = "ORDER";

//Incident Type
const ADMIN_ROLE = "ADMIN";
const USER_ROLE = "USER";

module.exports = {
  RESOLVED_INCIDENT,
  PENDING_INCIDENT,
  DOUBT_INCIDENT,
  INTEGRATION_INCIDENT,
  ORDER_INCIDENT,
  ADMIN_ROLE,
  USER_ROLE
};
